// File: Mux.v
// Generated by MyHDL 0.11.49
// Date: Fri Oct 11 17:49:31 2024


`timescale 1ns/10ps

module Mux (
    z,
    a,
    b,
    sel
);


output [7:0] z;
reg [7:0] z;
input [7:0] a;
input [7:0] b;
input sel;




always @(a, sel, b) begin: MUX_MUXLOGIC
    if ((sel == 1)) begin
        z = a;
    end
    else begin
        z = b;
    end
end

endmodule
